language: cpp

env:
  global:
    secure: "VEhB0Ejwd7HRwJp/9M7ZM/C6ChX+lQICeLX+YJvItV5+Iv4q/T7RkP0nEpuWhzqpXlNY+hBSAf8zu/dgcBNBfCPPO+QSS5T8JTvLVes/e4yGbshhpmq6gmQzqf81/AdilXVSmA+PO66QnoXELmQghgIneVAY2iywGHXpFTJ1U0lFHsbf+dZfLzJ+UrkZnSxTXivzOdse6d+6Iop2a3Uv2BUMmbvskjFhNYjWHy8G8ukscQjfNWz12bnqXlT1u+V7Oe/XKrOTsQPVBw2hp+KfMeg2R4QvDSXdS8Tc8pi2gWyykmrDBvd66UEfGtewwdYwmv8cmw+d+ShVEkmy2efrlk78FvHhRfkMSwRF8P5ZU6KjldogtfS6LPhdp/k4UMim/j9p+kRDgRuGUKcV7TugrcrXh3J+5voNuKH9nMjfO9xlZPbDqahbEoNRviYQTszX+MARkwiSRRHdMCxur0bENVJYezAjR2MKs4joHD1/bm2XUAsSX0TYY/hTJA+hJVKpx8evQx6qwjW7NSaCMI1gCi5UgQIBnWwkM2fLV2ZBPs/AxZzqwUaFplvLk2SdXOOU51qn6ciBkZaCzvda7WnVp50Eybu7mKsTYYpqmNmj3o4cq5ubbjke88g0yHHLnwTtjo3EpVHgvJv37stIYS4fmmfSD1fx7C8s1EJiB2e15tE="

matrix:
  include:
  - os: osx
    name: Build
    osx_image: xcode10.2
    compiler: clang
    script:
    - xcodebuild -configuration Debug
    - xcodebuild -configuration Release
  - os: osx
    name: "Analyze Coverity"
    osx_image: xcode10.2
    compiler: clang

    before_install:
      - curl -Ls https://entrust.com/root-certificates/entrust_l1k.cer -o ~/entrust_l1k.crt || exit 1
      - curl -LS https://curl.haxx.se/ca/cacert.pem -o ~/cacert.pem || exit 1
      - cat ~/entrust_l1k.crt >> ~/cacert.pem || exit 1
      - echo "cacert=\"$HOME/cacert.pem\"" > ~/.curlrc || exit 1
      - echo "ca_certificate=$HOME/cacert.pem" > ~/.wgetrc || exit 1

    script:
      - echo "This script runs coverity..."
    addons:
      coverity_scan:
        project:
          name: AppleIntelWifi
          description: adapter build
        notification_email: "$NOTIFICATION_EMAIL"
        build_command_prepend: src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/covstrap.sh)
          && eval "$src" || exit 1
        build_command: xcodebuild -configuration Release
        branch_pattern: master
  - os: osx
    name: Lint
    osx_image: xcode10.2
    compiler: clang
    script:
    - pip3 install cpplint # i hope python3 is installed lol
    - ./scripts/lint.sh
